module.exports = {
    ALL_USER: "ALL_USER",
    MESSAGE_SENT: "MESSAGE_SENT",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    USER_TYPING: "USER_TYPING",
    TYPING: "TYPING",
    LOGOUT: "LOGOUT",
    ALIVE: "ALIVE"
}