module.exports = {
    MESSAGE_SENT: "MESSAGE_SENT",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    TYPING: "TYPING",
    LOGOUT: "LOGOUT"
}